### ISSUE TITLE
Endpoint /User/{userid}/UAC broken

### ISSUE THREAD

**Issue by meldau** [TobitSoftware/chayns-backend#8]
Suddenly the Endpoint returns
{message:"Missing AccessToken.",errorGuid:"26d051bc-8547-48be-b7cd-1713eee358b6"}

There was no change made on my side, so the token could be lost. I tried bearer on v1 and Basic on v2. Please repair quickly. Everthing is broken now 👎 

@pjanning

**Comment by meldau** [comment]
"GET https://api.chayns.net/v2.0/{LocationID}/AccessToken" ist also broken. It returns a 3605 characters long string of empty spaces (this: "


    ") Maybe this correlates...

**Comment by pjanning** [comment]
The bug is fixed right now. Everything works again.
